# Copyright (C) 2026 loteran
# SPDX-License-Identifier: GPL-3.0-or-later

"""
pw_quirks.py — Per-device WirePlumber hardware quirks.

Some Arctis devices need a small WirePlumber ALSA monitor rule to work
around a hardware/USB quirk. Currently the only quirk is the ALSA capture
headroom override for the Nova Pro Wireless (issue #105): its USB playback
SYNC endpoint has no explicit feedback, which produces audible crackle on
some systems unless ``api.alsa.headroom`` is raised.

The quirk is expressed per-device via the optional ``alsa_headroom`` key in
the device YAML (see ``config.DeviceConfiguration.alsa_headroom``) and
applied here by writing a WirePlumber ``.conf.d`` fragment. WirePlumber is
restarted — never the whole PipeWire stack — and only when the fragment's
content actually changed, to avoid disrupting active audio streams on every
device (re)attach.
"""
from __future__ import annotations

import logging
import re
import shutil
import subprocess
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from arctis_sound_manager.config import DeviceConfiguration

_log = logging.getLogger(__name__)

_WP_CONF_DIR = Path.home() / ".config" / "wireplumber" / "wireplumber.conf.d"
_HEADROOM_CONF_NAME = "91-asm-alsa-headroom.conf"
_NO_SUSPEND_CONF_NAME = "92-asm-no-suspend.conf"
_STREAM_RESTORE_CONF_NAME = "93-asm-no-stream-restore.conf"

# The `monitor.alsa.rules` .conf.d syntax used below requires WirePlumber's
# Lua5 config engine, shipped since 0.5. Older WirePlumber (0.4.x) uses a
# different config format entirely — skip rather than write a fragment it
# can't parse.
_MIN_WIREPLUMBER_VERSION = (0, 5)


def _wireplumber_version() -> tuple[int, int] | None:
    """Return the installed WirePlumber's (major, minor) version, or None if
    the binary is missing or its output could not be parsed."""
    try:
        # Absolute path + close_fds=False pin the posix_spawn path so this never
        # fork()s the libusb-active daemon (issue #123).
        result = subprocess.run(
            [shutil.which("wireplumber") or "wireplumber", "--version"],
            capture_output=True, text=True, timeout=5, close_fds=False,
        )
    except (FileNotFoundError, OSError, subprocess.TimeoutExpired) as exc:
        _log.info("pw_quirks: could not run 'wireplumber --version' (%s)", exc)
        return None

    output = (result.stdout or "") + (result.stderr or "")
    match = re.search(r"(\d+)\.(\d+)", output)
    if not match:
        _log.info("pw_quirks: could not parse WirePlumber version from %r", output.strip())
        return None
    return int(match.group(1)), int(match.group(2))


def _render_headroom_conf(headroom: int) -> str:
    return (
        "# Auto-generated by Arctis Sound Manager — DO NOT EDIT\n"
        "# ALSA headroom quirk (issue #105): the device's USB SYNC endpoint has\n"
        "# no explicit feedback, which can produce audible crackle. Raising\n"
        "# api.alsa.headroom compensates for the missing feedback.\n"
        "monitor.alsa.rules = [\n"
        "  { matches = [\n"
        "      { node.name = \"~alsa_output.*SteelSeries.*\" }\n"
        "    ]\n"
        "    actions = {\n"
        f"      update-props = {{ api.alsa.headroom = {headroom} }}\n"
        "    }\n"
        "  }\n"
        "]\n"
    )


def apply_alsa_headroom_quirk(device_config: "DeviceConfiguration") -> bool:
    """Write, update or remove the WirePlumber ALSA headroom quirk fragment for
    *device_config*.

    - ``device_config.alsa_headroom is None`` → remove the fragment if present
      (cleanup: e.g. the previously-attached device needed the quirk, the
      newly-attached one doesn't).
    - otherwise → write/update the fragment with that headroom value.

    WirePlumber is restarted via :mod:`service_control` (never plain
    ``systemctl``/``dinitctl`` and never the full PipeWire stack) only when
    the fragment's content actually changed on disk. Requires WirePlumber
    >= 0.5 for the fragment's Lua5 syntax; older/undetectable versions are
    skipped with an info log (no fragment is written, nothing is removed
    beyond what a missing-quirk cleanup already does).

    Returns True if a change was made on disk (and WirePlumber was
    restarted), False otherwise.
    """
    conf_path = _WP_CONF_DIR / _HEADROOM_CONF_NAME
    headroom = getattr(device_config, "alsa_headroom", None)

    if headroom is None:
        return _remove_headroom_conf(conf_path)

    version = _wireplumber_version()
    if version is None or version < _MIN_WIREPLUMBER_VERSION:
        _log.info(
            "pw_quirks: ALSA headroom quirk requires WirePlumber >= %s "
            "(detected: %s) — skipping.",
            ".".join(map(str, _MIN_WIREPLUMBER_VERSION)), version,
        )
        return False

    new_content = _render_headroom_conf(headroom)
    old_content = conf_path.read_text() if conf_path.exists() else None
    if old_content == new_content:
        return False

    try:
        conf_path.parent.mkdir(parents=True, exist_ok=True)
        conf_path.write_text(new_content)
    except OSError as exc:
        _log.warning("pw_quirks: could not write %s: %s", conf_path, exc)
        return False

    _log.info(
        "pw_quirks: applied ALSA headroom=%d quirk for %s (issue #105).",
        headroom, getattr(device_config, "name", "?"),
    )
    _restart_wireplumber()
    return True


def _render_no_suspend_conf() -> str:
    return (
        "# Auto-generated by Arctis Sound Manager — DO NOT EDIT\n"
        "# ALSA tuning for the physical Arctis sink.\n"
        "#\n"
        "# session.suspend-timeout-seconds used to be pinned to 0 here\n"
        "# (#223/#230 class): with every ASM channel built node.passive, one\n"
        "# channel pausing could suspend/resume the shared physical sink under\n"
        "# a channel that never went idle itself, which was audible as that\n"
        "# channel going briefly or persistently silent. node.passive was\n"
        "# removed everywhere in v1.4.21 (see CHANGELOG) — nothing upstream of\n"
        "# this sink ever lets it go idle on its own any more, so that failure\n"
        "# mode cannot recur and the override serves no purpose. #180 (the\n"
        "# headset's own auto-off timer, which this override also blocked\n"
        "# outright — see #223/#230 class notes in idle_detect.py) is instead\n"
        "# being restored the explicit way: ASM itself decides when the whole\n"
        "# graph has been idle long enough and releases the last hop into this\n"
        "# sink (idle_detect.py, sonar_to_pipewire.release_physical_output_links),\n"
        "# rather than ever letting WirePlumber's own suspend heuristic decide.\n"
        "#\n"
        "# api.alsa.period-size stays doubled to 128 (up from ALSA's default\n"
        "# 64-frame period): a DualSense/DS5Dongle gamepad on a shared USB\n"
        "# controller had its HID reports measurably delayed by this sink's USB\n"
        "# isochronous transfer frequency; halving that frequency frees bus time\n"
        "# for the gamepad's polling, at the cost of a small amount of extra\n"
        "# audio latency (inaudible here). This is unrelated to the suspend\n"
        "# question above and applies regardless of it.\n"
        "monitor.alsa.rules = [\n"
        "  { matches = [\n"
        "      { node.name = \"~alsa_output.*SteelSeries.*\" }\n"
        "    ]\n"
        "    actions = {\n"
        "      update-props = { api.alsa.period-size = 128 }\n"
        "    }\n"
        "  }\n"
        "]\n"
    )


def apply_no_suspend_quirk() -> bool:
    """Write the WirePlumber fragment tuning the physical Arctis ALSA sink
    (see :func:`_render_no_suspend_conf` for what it currently does and why
    its name has outlived its original purpose — kept to avoid orphaning the
    fragment file an older ASM version already wrote for users upgrading).

    Not gated by a per-device YAML flag like :func:`apply_alsa_headroom_quirk`:
    it is a general fix, wanted whenever ASM manages a device, not a
    hardware-specific tuning value. Idempotent — a no-op when the fragment on
    disk already matches.

    Returns True if a change was made on disk (and WirePlumber was
    restarted), False otherwise.
    """
    version = _wireplumber_version()
    if version is None or version < _MIN_WIREPLUMBER_VERSION:
        _log.info(
            "pw_quirks: no-suspend quirk requires WirePlumber >= %s "
            "(detected: %s) — skipping.",
            ".".join(map(str, _MIN_WIREPLUMBER_VERSION)), version,
        )
        return False

    conf_path = _WP_CONF_DIR / _NO_SUSPEND_CONF_NAME
    new_content = _render_no_suspend_conf()
    old_content = conf_path.read_text() if conf_path.exists() else None
    if old_content == new_content:
        return False

    try:
        conf_path.parent.mkdir(parents=True, exist_ok=True)
        conf_path.write_text(new_content)
    except OSError as exc:
        _log.warning("pw_quirks: could not write %s: %s", conf_path, exc)
        return False

    _log.info("pw_quirks: applied no-suspend quirk for the physical ALSA sink (#223/#230).")
    _restart_wireplumber()
    return True


def _render_no_stream_restore_conf() -> str:
    return (
        "# Auto-generated by Arctis Sound Manager — DO NOT EDIT\n"
        "# WirePlumber restores per-node volume/mute/channelMap from its\n"
        "# stream-properties database on every (re)connect. For the HeSuVi\n"
        "# virtual-surround effect nodes this is a foot-gun: a one-off volume\n"
        "# change (e.g. a slider drag picked up while debugging HRIR profiles)\n"
        "# gets silently re-applied after every ASM rebuild, making Game and\n"
        "# Media chains permanently unequal (-10.7 dB on Game was traced to\n"
        "# exactly this). Disable stream restore for those nodes so ASM stays\n"
        "# the single source of truth for their level.\n"
        "#\n"
        "# Same reasoning covers the ASM virtual sinks (Arctis_Game/Chat/Media):\n"
        "# their volume is owned by channel_volumes.json (restored by ASM on\n"
        "# every loopback recreate), and a stale WP snapshot overwrites the user's\n"
        "# saved level with whatever the sink last happened to be at — observed as\n"
        "# the game channel drifting back up after every reconnect while the user\n"
        "# had turned it down. WP must not win that race.\n"
        "stream.rules = [\n"
        "  {\n"
        "    matches = [\n"
        "      { node.name = \"~effect_input.virtual-surround-7.1-hesuvi*\" }\n"
        "      { node.name = \"~effect_output.virtual-surround-7.1-hesuvi*\" }\n"
        "      { node.name = \"~Arctis_Game\" }\n"
        "      { node.name = \"~Arctis_Chat\" }\n"
        "      { node.name = \"~Arctis_Media\" }\n"
        "      { node.name = \"~Arctis_Game_sink_out\" }\n"
        "      { node.name = \"~Arctis_Chat_sink_out\" }\n"
        "      { node.name = \"~Arctis_Media_sink_out\" }\n"
        "    ]\n"
        "    actions = {\n"
        "      update-props = { state.restore-props = \"false\" }\n"
        "    }\n"
        "  }\n"
        "]\n"
    )


def apply_no_stream_restore_quirk() -> bool:
    """Write the WirePlumber fragment disabling volume stream-restore for
    ASM's HeSuVi virtual-surround effect nodes **and** the Arctis virtual
    sinks (see :func:`_render_no_stream_restore_conf`).

    Without it WirePlumber remembers whatever volume those nodes last had and
    re-applies it after every (re)connect — so a stray -10.7 dB that once
    landed on the Game chain silently persisted forever, making Game/Media
    unequal, and a stale snapshot of the Game sink volume overrode the user's
    saved channel_volumes.json level after every loopback recreate. Unlike the
    shared physical ALSA sink (which keeps its normal restore so
    pavucontrol/ASM volumes behave), these internal effect nodes and virtual
    sinks must always come up at the level ASM controls (1.0 / the saved
    per-channel value).

    Not gated by a per-device YAML flag: wanted whenever ASM manages a device.
    Idempotent — a no-op when the fragment on disk already matches.

    Returns True if a change was made on disk (and WirePlumber was
    restarted), False otherwise.
    """
    version = _wireplumber_version()
    if version is None or version < _MIN_WIREPLUMBER_VERSION:
        _log.info(
            "pw_quirks: no-stream-restore quirk requires WirePlumber >= %s "
            "(detected: %s) — skipping.",
            ".".join(map(str, _MIN_WIREPLUMBER_VERSION)), version,
        )
        return False

    conf_path = _WP_CONF_DIR / _STREAM_RESTORE_CONF_NAME
    new_content = _render_no_stream_restore_conf()
    old_content = conf_path.read_text() if conf_path.exists() else None
    if old_content == new_content:
        return False

    try:
        conf_path.parent.mkdir(parents=True, exist_ok=True)
        conf_path.write_text(new_content)
    except OSError as exc:
        _log.warning("pw_quirks: could not write %s: %s", conf_path, exc)
        return False

    _log.info("pw_quirks: applied no-stream-restore quirk for the HeSuVi effect nodes and Arctis virtual sinks.")
    _restart_wireplumber()
    return True


def _remove_headroom_conf(conf_path: Path) -> bool:
    if not conf_path.exists():
        return False
    try:
        conf_path.unlink()
    except OSError as exc:
        _log.warning("pw_quirks: could not remove %s: %s", conf_path, exc)
        return False
    _log.info("pw_quirks: removed ALSA headroom quirk fragment (no longer needed).")
    _restart_wireplumber()
    return True


def _restart_wireplumber() -> None:
    from arctis_sound_manager import service_control as sc
    sc.restart("wireplumber", timeout=15)
