# Copyright (C) 2026 loteran
# SPDX-License-Identifier: GPL-3.0-or-later

"""Single source of truth for the SteelSeries Arctis udev rules.

Both packaging (PKGBUILD / RPM spec / debian/rules → scripts/generate_udev_rules.py)
and the runtime CLI (asm-cli udev write-rules / dump-rules) call into this
module so the on-disk format is identical regardless of how the rules were
generated.
"""
from __future__ import annotations

from pathlib import Path
from typing import Iterable

from ruamel.yaml import YAML

_RULE_TEMPLATE = (
    'SUBSYSTEM=="usb", ATTRS{{idVendor}}=="{vid}", '
    'ATTRS{{idProduct}}=="{pid}", MODE="0666", TAG+="uaccess", ATTR{{power/control}}="on", '
    'ATTR{{power/persist}}="0"'
)
# The access ACL half of the rules lives in its own, earlier-numbered file.
# Since systemd 258, ACLs for the "uaccess" tag are applied by udevd's uaccess
# builtin, which 73-seat-late.rules only runs for devices *already* tagged by
# then — a TAG+="uaccess" set from a 91- file is recorded but never acted on
# (#297). MODE= and the power attributes stay in the 91- file so they keep
# winning over earlier rules; this file only adds the ACL on top, so a
# foreign rule that forces the node back to 0660 no longer locks the user out.
# Systems without logind's uaccess (eudev / elogind) simply ignore the tag.
_UACCESS_RULE_TEMPLATE = (
    'SUBSYSTEM=="usb", ATTRS{{idVendor}}=="{vid}", '
    'ATTRS{{idProduct}}=="{pid}", TAG+="uaccess"'
)
_HEADER = '# Generated by Arctis Sound Manager'
_FOOTER_LABEL = 'LABEL="local_end"'


def _iter_yaml_files(paths: Iterable[Path]) -> Iterable[Path]:
    seen: set[Path] = set()
    for p in paths:
        try:
            if not p.is_dir():
                continue
            candidates = sorted(p.glob('*.yaml'))
        except OSError:
            # Unreadable folder (another user's home, stale network mount…):
            # skip it rather than aborting the whole rules generation.
            continue
        for f in candidates:
            real = f.resolve()
            if real in seen:
                continue
            seen.add(real)
            yield f


def load_devices(paths: Iterable[Path]) -> list[tuple[int, list[int], str]]:
    """Return [(vendor_id, [product_ids], name)] from every device YAML in *paths*.

    For each (vendor_id, name) the product ids are **unioned** across every file
    that declares it, in first-seen order. This deliberately differs from the
    daemon's first-match-wins profile resolution (load_device_configurations),
    and it exists to keep udev access from ever being narrower than the union of
    what any profile knows about (#146):

    - A stale ~/.config/arctis_manager/devices copy — the pre-#146 asm-setup
      wrote one on first run — shares a family's (vendor_id, name) with the
      bundled profile. First-match-wins let that old copy *shadow* the bundled
      PIDs, so a product id added to the package in a later release (e.g. the
      Nova 7P Gen 2's 0x2298) never reached the rules file even after upgrading.
      Unioning means the stale copy can no longer hide a newer packaged PID.
    - A product id a user genuinely hand-added to an override is emitted too —
      "add a product id" grants USB access as intended, instead of being lost.

    An extra access rule (MODE=0666) for a PID the daemon would not actually
    drive is harmless, so a superset is the safe direction for udev
    specifically. Packaging callers passing only the bundled SRC folder are
    unaffected and still get a deterministic order.
    """
    yaml = YAML(typ='safe')
    pids_by_key: dict[tuple[int, str], list[int]] = {}
    order: list[tuple[int, str]] = []
    for f in _iter_yaml_files(paths):
        data = yaml.load(f)
        device = data['device']
        # A generic profile stands in for "no USB device at all" (#189): it has
        # no vendor id and no product ids, so there is nothing to grant access
        # to. Skipped rather than tolerated with defaults — a rule for
        # vendor 0000 would be meaningless, and reading a missing key here used
        # to abort the whole generator, taking the packaging build with it.
        if device.get('generic', False):
            continue
        vid = int(device['vendor_id'])
        name = str(device['name'])
        key = (vid, name)
        if key not in pids_by_key:
            pids_by_key[key] = []
            order.append(key)
        merged = pids_by_key[key]
        for p in device['product_ids']:
            pid = int(p)
            if pid not in merged:
                merged.append(pid)
    return [(vid, pids_by_key[(vid, name)], name) for (vid, name) in order]


def _render(devices: list[tuple[int, list[int], str]], template: str) -> str:
    lines: list[str] = [_HEADER, '', 'ACTION=="remove", GOTO="local_end"']
    for vid, pids, name in devices:
        lines.append('')
        lines.append(f'# {name}')
        for pid in pids:
            lines.append(template.format(vid=f'{vid:04x}', pid=f'{pid:04x}'))
    lines += ['', _FOOTER_LABEL, '']
    return '\n'.join(lines)


def render_rules(devices: list[tuple[int, list[int], str]]) -> str:
    """Render udev rules text from a list of (vendor_id, [pids], name) tuples."""
    return _render(devices, _RULE_TEMPLATE)


def render_uaccess_rules(devices: list[tuple[int, list[int], str]]) -> str:
    """Render the 70- uaccess-only rules file for the same device list."""
    return _render(devices, _UACCESS_RULE_TEMPLATE)


def generate_rules(paths: Iterable[Path]) -> str:
    """Convenience: load + render in one call."""
    return render_rules(load_devices(paths))


def generate_uaccess_rules(paths: Iterable[Path]) -> str:
    """Convenience: load + render the uaccess-only file in one call."""
    return render_uaccess_rules(load_devices(paths))
